import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Button } from '@/components/Shared';
const ages = [['Infants', 'Providing your baby’s brain with a strong foundation for learning and growing.', '3-11 months'], ['Toddlers', 'Your child will explore the world around him and form relations with other children & adults.', '12-35 months'], ['Preschoolers', 'Providing your baby’s brain with a strong foundation for learning and growing.', '36-48 months'], ['Flex-Care', 'To meet the individual needs of each family, we also provide Pre-Care & After Care services.', '6-48 months']];
const photos = ['/assets/play.jpg', '/assets/learning.jpg', '/assets/child.jpg', '/assets/feature.jpg'];
export default function Home() {
  return <><Header /><main>
    <section className="hero"><span className="hero-gem gem-one" /><span className="hero-gem gem-two" /><span className="hero-gem gem-three" /><svg className="hero-brush" viewBox="0 0 1440 220" preserveAspectRatio="none" aria-hidden="true"><path d="M-28 145C198 93 350 202 559 139S918 23 1123 83s254 40 351-22" /></svg><div className="hero-orbit"><img className="hero-butterfly" src="/assets/butterfly.png" alt=""/><p className="hero-first">The First &amp; Only</p><h1>Reggio Emilia</h1><h2>Inspired Nursery School</h2><h2>In the Sultanate of Oman</h2><p>Education is a right and all children have potential</p><Button href="/about/">Learn More</Button></div></section>
    <section className="pillars"><div className="pillar-list">{['Home-like Environment', 'Safe & Secure', 'Quality Educators', 'Play to Learn', 'Modern & Innovative'].map((item, i) => <article key={item}><span>{i + 1}.</span><h3>{item}</h3></article>)}</div><img src="/assets/people.svg" alt="" /><Button href="/about/">Learn More</Button></section>
    <section className="ages"><img className="age-face" src="/assets/right-cut.svg" alt="" /><div className="ages-heading"><h2>Ages</h2><p>We meet kids where they are.</p></div><div className="age-grid">{ages.map(([title, description, age], i) => <article key={title} className="age"><h3>{title}</h3><img src={photos[i]} alt="" /><p>{description}</p><small>{age} · 8:30 - 1:30h</small><i /></article>)}</div></section>
    <section className="program-intro"><div><p className="eyebrow">Our Programs</p><p>Shomoukh follows the Early Years Foundation Stage (EYFS) curriculum, a UK-based system of education or framework which sets the goals in terms of learning and development for children from birth to five years of age. It also sets out the standards for ensuring the welfare of all students within safe and supportive environments.</p><p>In our Nursery Schools, the EYFS program integrates well with the Reggio Emilia philosophy, that sets the standards for a project-based education, where each child is driven by their own interests.</p></div><div><p className="eyebrow">The Teacher</p><p>Teachers at Shomoukh Nursery Schools are researchers: learning alongside the children. They observe and document the children’s learning, whilst nurturing their curiosity and encouraging their thoughts, ideas, and actions through open-ended activities and explorations.</p><p className="eyebrow">The Environment<br />“The Third Teacher”</p><p>The classrooms and outdoor areas are spaces that offer provocations for learning, exploration, and play. Spaces are interconnected to support communication, curiosity, and interaction between children and adults.</p></div></section>
    <section className="values"><img src="/assets/people-two.svg" alt="" /><div><h2>We work everyday to empower your child</h2><p>Research-based curriculum and individual learning experiences are integral to all the programs at Shomoukh schools. Through dedication and nurturing, our teacher’s singular goal is to guide your child to meet their learning milestones and becoming lifelong learners.</p><Button href="/programs/">Programs</Button></div></section>
    <section className="tour"><img src="/assets/people-two.svg" alt="" /><div><h2>Come <span>over and look around.</span></h2><p>Interested in joining our new session? We are here to answer any questions you may have about our wonderful offerings. Please feel free to contact us either through our online inquiry form or pop in for a visit. We would love to book a tour at your convenience.</p><Button href="/schedule-a-tour/">Schedule a Tour</Button><Button href="/apply-online/">Join Our New Session</Button></div></section>
    <section className="closing-note"><img src="/assets/butterfly.png" alt="" /><p>Every child is capable, curious and full of potential.</p><Button href="/contactus/">Talk to us</Button></section>
  </main><Footer /></>;
}
